version: 2
jobs:
  build:
    macos:
      xcode: '10.0.0'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            brew install swiftlint
      - run:
          name: Generate Xcode project
          command: |
            swift package generate-xcodeproj
      - run:
          name: Build for release
          command: |
            swift build -c release
      - run:
          name: Run tests
          command: xcodebuild test -scheme Connect-Package -enableCodeCoverage YES
      - run:
          name: Send test coverage report
          command: bash <(curl -s https://codecov.io/bash)
